### ISSUE TITLE
uninitialzed constant Pagy::VARS

### ISSUE THREAD

**Issue by mostafaSYR** [ddnexus/pagy#80] opened 2018-08-27 11:50 UTC
/home/cn/.rvm/gems/ruby-2.5.1/gems/pagy-0.19.0/lib/pagy/extras/shared.rb:8:in `<class:Pagy>': uninitialized constant Pagy::VARS (NameError).

Hey all, everything was just fine, as the version 0.16.0, until I ran 'bundle update'. With the new version I get this errors when I try to run the server. I guess its just a typo, anyway I downgraded the gem to 0.16.0 and things got better. And I thought I should tell warn you guys.
Thanks in Advance

**Comment by ddnexus** [comment] 2018-08-27 14:36
Hi @mostafaSYR ,
That file is loaded only after pagy, by any fronted extension in the initializer file, so it should not happen. How are you using pagy?

**Comment by mostafaSYR** [comment] 2018-09-03 12:34
Hi @ddnexus,.

sorry for the late reply, Im using pagy in this way, 
wrote pagy in GemFile, got the '0.14.0' version.
@pagy, @records = pagy(Product.some_scope) in the controller.
<%== pagy_nav(@pagy) %> in the view. 
And then everything went just well.

As I tried to use some bootstrap, I tried to write in the application.rb 
require 'pagy/extras/bootstrap'  and everything was ok as well, untill I updated the gems and got the 0.19.0 version, I stated getting this error.

**Comment by ddnexus** [comment] 2018-09-03 12:49
You should never require anything in `application.rb`! (It looks like you probably required the extra before the `Bundler.require...` statement, which is the reason of your problem)

You should copy and uncomment/customize the [pagy initializer](https://github.com/ddnexus/pagy/blob/master/lib/config/pagy.rb) file in the `config/initializers` dir of your app, and it should work properly.

I can confirm that there is no issue with a rails app loading any frontend extension (including bootstrap), so I am going to close this issue. Please, reopen if needed.

**Closed by ddnexus** 2018-09-03 12:49 UTC

**Comment by ryush00** [comment] 2022-02-08 11:33
If you come across this issue on 2022, you should change Pagy::VARS to Pagy::DEFAULT. it was changed at 5.0.0

**Comment by ddnexus** [comment] 2022-02-08 11:36
Yes Issue #340! Thank you @ryush00
