### ISSUE TITLE
Responsive extra with Turbolinks and pagy_array

### ISSUE THREAD

**Issue by alec-implicitdesign** [ddnexus/pagy#115] opened 2019-01-10 12:56 UTC
Please refer to [this](https://github.com/ddnexus/pagy/issues/64).  The same error is popping up again now using turbolinks and pagy_array.

It also looks like the code that fixed this issue originally has been removed, so I take it another solution was found?

**Comment by ddnexus** [comment] 2019-01-11 11:22
If I open a new empty tab, then go to a pagy url pasted in the address bar, it generates the error. After that if the tab is the same, it works as expected without errors.

The fix for this problem is still there untouched, so I suspect that in this particular case of the new tab, it was there even after the fix. Could you check that?

**Comment by ddnexus** [comment] 2019-01-11 11:41
I just found the problem... thinking about how to refactor it...

**Comment by ddnexus** [comment] 2019-01-13 05:30
The old #64 was not actually fixing the root cause, just mitgating it. Now cef823c should have fixed it. The fix is part of a few other improvements for javascript and AJAX that will go into the next release,

**Comment by alec-implicitdesign** [comment] 2019-01-22 12:48
As far as I understand this fix should be in 1.3?  I'm still getting errors:

`Uncaught TypeError: Cannot read property 'forEach' of undefined`

**Comment by ddnexus** [comment] 2019-01-22 14:53
I cannot reproduce that. Could you share a repo that produce that error?

**Comment by ddnexus** [comment] 2019-01-22 15:06
BTW, I assume the javascript served in your page is the last one, not cached somehow...

**Comment by ddnexus** [comment] 2019-01-22 17:15
Just create a new app with a pagy gem and initializer, plus the javascript part. You don't even need a db: you just set the :count in the controller action and render just the `@pagy` in the view. No need to list `@records`. 

Something like:

```ruby
  def responsive_test
    @pagy, _records = pagy(count: 1000)
  end
```
```erb
<%== pagy_responsive_nav(@pagy) %>
```

**Comment by ddnexus** [comment] 2019-01-22 17:31
OK, no need to create any repo. I think I understood the problem. It depends on how much stuff is in the page. Please try the `dev` branch.

**Comment by ddnexus** [comment] 2019-01-23 10:35
@alec-implicitdesign glad that it finally works. 

With "stuff in the page" I wasn't referring to the count nor the items per page: I was referring to the elements in the HTML page, or better, how long the page takes to get loaded. The `Pagy.responsive` function calls the `render` function as soon as the responsive `nav` gets on the page (after document.load), but the actual `container.clientWidth` gets set only when everything in the page gets its own dimensions. That depends on the other elements on the page and I suspect that it depends also from the particular layout and specific elements and CSS rules, and might even be different from browser to browser.

I didn't find a better way to ensure that the `container.cientWidth` gets a proper value before calling `render`, than checking it periodically from the `render` itself, till the page is done with calculating the dimensions. That just postpones the execution of the rest of the function till when there is a value for the `container.cientWidth`. It works well and doesn't affect anything else, but if you have a better way to do it, I am open to improve it.

**Closed** 2019-01-23 11:02 UTC
Labels: fixed

**Comment by alec-implicitdesign** [comment] 2019-01-23 12:40
Okay thanks for clarifying.  I will have a look at it when I get a moment and see if I can't find a way around a `setTimeout`.
