### ISSUE TITLE
Is there a configuration to only show pagination when there is more than one page?

### ISSUE THREAD

**Issue by evgenyneu** [ddnexus/pagy#405] opened 2022-08-18 00:50 UTC
Hi, is there a Page configuration to only show pagination with `pagy_nav(@pagy)` when there is more than one page? Of course, I can manually do this:

```
<% if @pagy.pages > 1 %>
    <%== pagy_nav(@pagy) %>
<% end %>
```

but I was wondering if this is already built into `pagy_nav`.

**Comment by ddnexus** [comment] 2022-08-18 01:32
Manually by design. Details [here](https://ddnexus.github.io/pagy/how-to#skip-single-page-navs)

**Comment by benkoshy** [comment] 2022-08-18 01:33
It's the only way:

You can try something like this if you wish.

```rb
<% if @pagy.pages > 1 %>
    <%== pagy_nav(@pagy) %>
<% else %>
    <%== pagy_info(@pagy) %>
<% end %>
```

(Typically we reserve issues for bug fixes. It doesn't sound like a bug so I would probably close this issue).

**Closed by ddnexus** 2022-08-18 01:32 UTC
