### ISSUE TITLE
Bug: include Pagy::Console throws can't modify frozen Hash

### ISSUE THREAD

**Issue by aslam** [ddnexus/pagy#481] opened 2023-03-08 14:17 UTC
### Before submitting...

- [X] I upgraded to the latest version of pagy
- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### I am providing...

- [X] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/docs/api/console)

- [ ] Plain ruby file that can run as `ruby my-problem.rb`

- [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)

- [ ] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)

- [ ] Link of my own branch forked from pagy, which contains an added test file

- [ ] Link of my own branch forked from [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)

- [ ] A `docker-compose` file that uses only docker images and no local context and runs with `docker-compose up`

### Description

About your application's environment
```
Rails version             7.0.4.2
Ruby version              ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
RubyGems version          3.3.7
Rack version              2.2.5
Middleware                Rack::Cors, ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActionDispatch::ServerTiming, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, ActionDispatch::RemoteIp, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, WebConsole::Middleware, ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper, Warden::Manager, ActionDispatch::Static
Environment               development
Database adapter          postgresql
Database schema version   20230223155302
```

```
*** LOCAL GEMS ***

pagy (6.0.1, 6.0.0, 5.10.1)
    Author: Domizio Demichelis
    Homepage: https://github.com/ddnexus/pagy
    License: MIT
    Installed at (6.0.1): /Users/syed/.rvm/gems/ruby-3.1.2
                 (6.0.0): /Users/syed/.rvm/gems/ruby-3.1.2
                 (5.10.1): /Users/syed/.rvm/gems/ruby-3.1.2

    The kick-ass pagination ruby gem
```

I have the following in the initialiser file:
```
# Pagy initializer file (6.0.0)                                # default
Pagy::DEFAULT[:items] = 15 # default

Pagy::DEFAULT[:metadata] = %i[ first_url page_url prev_url next_url last_url ]

Pagy::I18n.load({ locale: 'de', filepath: 'config/locales/pagy-de.yml' },
                { locale: 'en', filepath: 'config/locales/pagy-en.yml' })

# When you are done setting your own default freeze it, so it will not get changed accidentally
Pagy::DEFAULT.freeze
```

I am trying to use the `Pagy::Console` in irb:
```
$> rails c
Loading development environment (Rails 7.0.4.2)
3.1.2 :001 > require 'pagy/console'
 => true
3.1.2 :002 > include Pagy::Console
/Users/syed/.rvm/gems/ruby-3.1.2/gems/pagy-6.0.0/lib/pagy/console.rb:14:in `included': can't modify frozen Hash: {:page=>1, :items=>15, :outset=>0, :size=>[1, 4, 4, 1], :page_param=>:page, :params=>{}, :fragment=>"", :link_extra=>"", :i18n_key=>"pagy.item_name", :cycle=>false, :request_path=>"", :headers=>{:page=>"Current-Page", :items=>"Page-Items", :count=>"Total-Count", :pages=>"Total-Pages"}, :metadata=>[:first_url, :page_url, :prev_url, :next_url, :last_url], :steps=>false} (FrozenError)
3.1.2 :003 >
```

**Comment by benkoshy** [comment] 2023-03-08 21:22
```diff
#pagy.rb
# Pagy initializer file (6.0.0)                                # default
Pagy::DEFAULT[:items] = 15 # default

Pagy::DEFAULT[:metadata] = %i[ first_url page_url prev_url next_url last_url ]

Pagy::I18n.load({ locale: 'de', filepath: 'config/locales/pagy-de.yml' },
                { locale: 'en', filepath: 'config/locales/pagy-en.yml' })

# When you are done setting your own default freeze it, so it will not get changed accidentally
- Pagy::DEFAULT.freeze
+ # Remove the default freeze line
```

**Comment by benkoshy** [comment] 2023-03-08 21:58
### The Cause

I suspect this is caused here:

https://github.com/ddnexus/pagy/blob/73c1ca2f1f21c89d059e427976a6a3171654c8de/lib/pagy/console.rb#L14

We are modifying the hash after it's been frozen.

**Comment by ddnexus** [comment] 2023-03-08 23:13
The `Pagy::Console` is meant to supply a mock environment to pagy, so it would work even without any app or configuration. If you actually want to just try pagy in its mock environment, you could just use `irb` for a quick glance into pagy (without loading the rails env).

The use of `Pagy::Console` in the `rails c` is kind of hybrid. When you use the rails console, you are loading the rails environment (and the `pagy.rb` initializer/configuration), hence you should be able to use pagy without the `Pagy::Console`, by just running your own controllers and helpers in the console for a truthy/non-mocked output.

However if you actually want to use it in the `rails c` you can temporarily comment out the `Pagy::DEFAULT.freeze` , so allowing `Pagy::Console` to set the `DEFAULT[:url]`, or set it yourself to `nil` in the console, in order to avoid changing the default `pagy_url_for` behavior.

I don't know whether using it with `rails c` would provide any advantage compared to use the actual controller/helper methods. If it does, please let me know. If it doesn't we should remove the rails console mention from the `Pagy::Console` doc and eventually add a note explaining that there is no point to use it with an app environment.

**Comment by aslam** [comment] 2023-03-08 23:56
Temporarily commenting out the `Pagy::DEFAULT.freeze` line works. Thanks for the tip.

I was trying out a few things in setting the JSON response of the collection serializer using the `pagy_metadata`. I Thought `Pagy::Console` would be handy here and believe it would be.

Would there be a better way to make this module readily useful in `rails c`? Any ideas on what could be possible if you believe this module is useful to stay? I could try and put something for you to have a look at.

**Comment by ddnexus** [comment] 2023-03-09 00:11
> Would there be a better way to make this module readily useful in rails c?

Pagy is agoistic, so no rails outside of the doc.

> Any ideas on what could be possible if you believe this module is useful to stay? I could try and put something for you to have a look at.

I don't understand anything of what you mean here 🙃

**Comment by ddnexus** [comment] 2023-03-09 01:15
My thoughts about rais env so far are that either you need the whole rails env to check the real pagy output, and in that case you don't need `Pagy::Console` because you have everything accessible in the `rails c`, OR you just want to play with a mocked env in order to familiarize with the pagy stuff, and in that case you don't need the rails env, hence `irb` would be enough.

Mixing environments would just be confusing and would require more work than what you may save typing IMO.

Am I missing anything?

**Comment by benkoshy** [comment] 2023-03-09 02:24
Closing in favour of #483. 

Pls LMK if I've missed the mark. I've also simplified the wording.

**Closed** 2023-03-09 10:42 UTC
Labels: invalid, documentation
