### ISSUE TITLE
Using ArgumentError is causing side effects with handling our API

### ISSUE THREAD

**Issue by krtschmr** [ddnexus/pagy#171] opened 2019-07-29 03:34 UTC
We use Pagy for our API and it works great. however, our API also rescues from `ArgumentError`. Because Pagy is using `ArgumentError` internally and then rescues itself and throws the `OverflowError` we are unable catch the `OverFlowError`
```

  rescue_from Pagy::OverflowError do
    render status: 404, json: {errors: ["No more pages"] }
  end

  rescue_from ArgumentError do |e|
    render status: 400, json: {errors: e}
  end

```

our fix is, but this doesn't really look so good.  I wonder if Pagy should have his own `Pagy::ArgumentError` ?

```
  rescue_from ArgumentError do |e|
    if e.is_a?(Pagy::OverflowError)
      render status: 404, json: {errors: ["No more pages"] }
    else
      render status: 400, json: {errors: e}
    end
  end


```

**Comment by ddnexus** [comment] 2019-07-29 09:05
Hi @krtschmr,
the reasons all errors are a subclass of `ArgumentError` are 2: 

1. any error raised in Pagy is generated by passing a wrong argument to the constructor, hence they are ultimately an `ArgumentError` 
2. before the recent exception refactoring, all the errors raised by Pagy were directly `ArgumentError` hence, changing the base-class would have broken all the legacy rescues, so they are still rescue-able by `ArgumentErrors`

> I wonder if Pagy should have his own `Pagy::ArgumentError` ?

It has `Pagy::VariableError` for all pagy generated `ArgumentError`s. However `Pagy::VariableError` is a subclass of `ArgumentError` so if you catch `ArgumentError` you have still to check. 

However, if you catch the error in cascade starting from the most nested subclass, you don't have to write any weird condition. For example:

```ruby
def something
  ...
rescue Pagy::OverflowError => e
  puts "got a Pagy::OverflowError"
  ...
rescue Pagy::VariableError => e
  puts "got a generic Pagy::VariableError (not from overflow)"
  ...
rescue ArgumentError => e
  puts "got an ArgumentError (not raised from Pagy)"
  ...
end
```
Wouldn't that solve your problem?

**Comment by ddnexus** [comment] 2019-07-29 09:17
BTW, I just notice that you use `rescue_from` so your solution is even simpler. You have just to invert the position of the `rescue_from` calls, since the highest priority assigned by `rescue_from` should be the latter. 

In other words, you start with the catch-all rescue_from, then add more specific rescues (in reversed order of priority compared to the rescue of the previous example).

This should solve your problem.

**Comment by ddnexus** [comment] 2019-08-01 13:15
Closing this issue, assuming the problem is solved. If not, please re-open it.

**Closed by ddnexus** 2019-08-01 13:15 UTC
